//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHampson.Cascara {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHampson.Cascara.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cannot be empty..
        /// </summary>
        internal static string ArgumentExceptionEmptyList {
            get {
                return ResourceManager.GetString("ArgumentExceptionEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty or null..
        /// </summary>
        internal static string ArgumentExceptionEmptyPath {
            get {
                return ResourceManager.GetString("ArgumentExceptionEmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML data cannot be empty or null..
        /// </summary>
        internal static string ArgumentExceptionEmptyXmlData {
            get {
                return ResourceManager.GetString("ArgumentExceptionEmptyXmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a non-negative integer..
        /// </summary>
        internal static string ArgumentExceptionNonNegativeInteger {
            get {
                return ResourceManager.GetString("ArgumentExceptionNonNegativeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a value type..
        /// </summary>
        internal static string ArgumentExceptionValueType {
            get {
                return ResourceManager.GetString("ArgumentExceptionValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal name for collections used on a symbol that does not represent a collection!.
        /// </summary>
        internal static string InvalidOperationExceptionReservedSymbolName {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionReservedSymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; cannot have an empty value..
        /// </summary>
        internal static string LayoutExceptionEmptyAttribute {
            get {
                return ResourceManager.GetString("LayoutExceptionEmptyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Binary Layout..
        /// </summary>
        internal static string LayoutExceptionEmptyLayout {
            get {
                return ResourceManager.GetString("LayoutExceptionEmptyLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty struct..
        /// </summary>
        internal static string LayoutExceptionEmptyStruct {
            get {
                return ResourceManager.GetString("LayoutExceptionEmptyStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root element name for Binary Layout. Must have a root element named &apos;{0}&apos;..
        /// </summary>
        internal static string LayoutExceptionInvalidRootElement {
            get {
                return ResourceManager.GetString("LayoutExceptionInvalidRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layout named &apos;{0}&apos; already exists in the namespace..
        /// </summary>
        internal static string LayoutExceptionLayoutExists {
            get {
                return ResourceManager.GetString("LayoutExceptionLayoutExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required attribute &apos;{0}&apos;..
        /// </summary>
        internal static string LayoutExceptionMissingRequiredAttribute {
            get {
                return ResourceManager.GetString("LayoutExceptionMissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown attribute &apos;{0}&apos;..
        /// </summary>
        internal static string LayoutExceptionUnknownAttribute {
            get {
                return ResourceManager.GetString("LayoutExceptionUnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type or directive &apos;{0}&apos;..
        /// </summary>
        internal static string LayoutExceptionUnknownType {
            get {
                return ResourceManager.GetString("LayoutExceptionUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML data for Binary Layout..
        /// </summary>
        internal static string LayoutExceptionXmlLoadFailure {
            get {
                return ResourceManager.GetString("LayoutExceptionXmlLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the element of a symbol that does not represent a collection..
        /// </summary>
        internal static string NotSupportedExceptionElementAccess {
            get {
                return ResourceManager.GetString("NotSupportedExceptionElementAccess", resourceCulture);
            }
        }
    }
}
